import React from 'react';
import Layout from '../../../utils/components/layout/layout';
import useTranslation from "../../../utils/hooks/useTranslation";
import withLocale from "../../../utils/hocs/withLocale";

const eula = () => {
  const { t } = useTranslation();

  return (
      <Layout banner={{
        caption: t('eula-page-caption')
      }}>
        <h2>
          {t('eula-heading')}
        </h2>
        <h3>
          {t('eula-subheading-important')}
        </h3>
        <p>
          {t('eula-important-part-1')}
          <b>
            {t('eula-important-part-2')}
          </b>
        </p>
        <h3>
          {t('eula-subheading-recitals')}
        </h3>
        <p>
          {t('eula-recitals-part-1', {
            wheras: <b>
              {t('eula-recitals-part-1-wheras')}
            </b>
          })}
          <b>
            {t('eula-recitals-part-2')}
          </b>
        </p>
        <h3>
          {t('eula-subheading-definitions')}
        </h3>
        <p>
          {t('eula-definitions-part-1')}
        </p>
        <h3>
          {t('eula-subheading-grantrights')}
        </h3>
        <p>
          {t('eula-grantrights-part-1')}
        </p>
        <h3>
          {t('eula-subheading-delivery')}
        </h3>
        <p>
          <b>
            {t('eula-delivery-software')}
          </b>
          {t('eula-delivery-software-para')}
        </p>
        <p>
          <b>
            {t('eula-delivery-docs')}
          </b>
          {t('eula-delivery-docs-para')}
        </p>
        <h3>
          {t('eula-subheading-modifications')}
        </h3>
        <p>
          <b>
            {t('eula-modifications-updates')}
          </b>
          {t('eula-modifications-updates-para')}
        </p>
        <p>
          <b>
            {t('eula-modifications-other')}
          </b>
          {t('eula-modifications-other-para')}
        </p>
        <p>
          <b>
            {t('eula-modifications-title')}
          </b>
          {t('eula-modifications-title-para')}
        </p>
        <h3>
          {t('eula-subheading-copies')}
        </h3>
        <p>
          <b>
            {t('eula-copies-human')}
          </b>
          {t('eula-copies-human-para')}
        </p>
        <p>
          <b>
            {t('eula-copies-machine')}
          </b>
          {t('eula-copies-machine-para')}
        </p>
        <h3>
          {t('eula-subheading-licensefees')}
        </h3>
        <p>
          <b>
            {t('eula-licensefees-fee')}
          </b>
          {t('eula-licensefees-fee-para')}
        </p>
        <p>
          <b>
            {t('eula-licensefees-taxes')}
          </b>
          {t('eula-licensefees-taxes-para')}
        </p>
        <h3>
          {t('eula-subheading-protection')}
        </h3>
        <p>
          <b>
            {t('eula-protection-security')}
          </b>
          {t('eula-protection-security-para')}
        </p>
        <p>
          <b>
            {t('eula-protection-proprietary')}
          </b>
          {t('eula-protection-proprietary-para')}
        </p>
        <p>
          <b>
            {t('eula-protection-noreverse')}
          </b>
          {t('eula-protection-noreverse-para')}
        </p>
        <p>
          <b>
            {t('eula-protection-ownership')}
          </b>
          {t('eula-protection-ownership-para')}
        </p>
        <h3>
          {t('eula-subheading-confidentiality-1')}
        </h3>
        <p>
          <b>
            {t('eula-confi-1-ack')}
          </b>
          {t('eula-confi-1-ack-para')}
        </p>
        <p>
          <b>
            {t('eula-confi-1-maintenance')}
          </b>
          {t('eula-confi-1-maintenance-para')}
        </p>
        <p>
          <b>
            {t('eula-confi-1-relief')}
          </b>
          {t('eula-confi-1-relief-para')}
        </p>
        <p>
          <b>
            {t('eula-confi-1-survival')}
          </b>
          {t('eula-confi-1-survival-para')}
        </p>
        <h3>
          {t('eula-subheading-warranties')}
        </h3>
        <p>
          <b>
            {t('eula-warranties-ownership')}
          </b>
          {t('eula-warranties-ownership-para')}
        </p>
        <p>
          <b>
            {t('eula-warranties-limited')}
          </b>
          {t('eula-warranties-limited-para')}
        </p>
        <p>
          <b>
            {t('eula-warranties-limitations')}
          </b>
          {t('eula-warranties-limitations-para')}
        </p>
        <p>
          <b>
            {t('eula-warranties-soleremedy')}
          </b>
          {t('eula-warranties-soleremedy-para')}
        </p>
        <p>
          <b>
            {t('eula-warranties-disclaimer')}
          </b>
          {t('eula-warranties-disclaimer-para')}
        </p>
        <p>
          <b>
            {t('eula-warranties-limitliability')}
          </b>
          {t('eula-warranties-limitliability-para')}
        </p>
        <h3>
          {t('eula-subheading-confidentiality-2')}
        </h3>
        <p>
          {t('eula-confi-2-para')}
        </p>
        <h3>
          {t('eula-subheading-default')}
        </h3>
        <p>
          <b>
            {t('eula-default-events')}
          </b>
          {t('eula-default-events-para')}
        </p>
        <p>
          <b>
            {t('eula-default-effective')}
          </b>
          {t('eula-default-effective-para')}
        </p>
        <p>
          <b>
            {t('eula-default-obligations')}
          </b>
          {t('eula-default-obligations-para')}
        </p>
        <p>
          <b>
            {t('eula-default-notices')}
          </b>
          {t('eula-default-notices-para')}
        </p>
        <h3>
          {t('eula-subheading-nonassign')}
        </h3>
        <p>
          {t('eula-nonassign-para')}
        </p>
        <h3>
          {t('eula-subheading-governing')}
        </h3>
        <p>
          {t('eula-governing-para')}
        </p>
        <h3>
          {t('eula-subheading-severability')}
        </h3>
        <p>
          {t('eula-severability-para')}
        </p>
        <h3>
          {t('eula-subheading-misc')}
        </h3>
        <p>
          <b>
            {t('eula-misc-para')}
          </b>
        </p>

      </Layout>
  );
};

export default withLocale(eula);
